# Generated by Django 4.0.4 on 2022-05-16 22:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jahorina', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='acitivity',
            name='name',
        ),
        migrations.AddField(
            model_name='acitivity',
            name='x',
            field=models.IntegerField(default=-1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='acitivity',
            name='y',
            field=models.IntegerField(default=-1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='category',
            name='root',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='skitrack',
            name='last_updated',
            field=models.DateField(default=datetime.datetime(2022, 5, 17, 0, 24, 28, 996209)),
        ),
        migrations.DeleteModel(
            name='RootCategory',
        ),
    ]
