# Generated by Django 4.0.4 on 2022-05-17 13:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jahorina', '0002_remove_acitivity_name_acitivity_x_acitivity_y_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='skitrack',
            name='comment',
            field=models.TextField(blank=True, default='Trenutno nema novih obavestenja', null=True),
        ),
        migrations.AlterField(
            model_name='acitivity',
            name='x',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='acitivity',
            name='y',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='skitrack',
            name='last_updated',
            field=models.DateField(default=datetime.datetime(2022, 5, 17, 15, 29, 12, 40024)),
        ),
    ]
