# Generated by Django 4.0.4 on 2022-05-22 10:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jahorina', '0002_alter_activity_x_alter_activity_y_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='message',
            field=models.CharField(default=' ', max_length=250),
        ),
        migrations.AlterField(
            model_name='skitrack',
            name='last_updated',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 22, 12, 7, 57, 273180)),
        ),
    ]
