# Generated by Django 4.0.4 on 2022-05-24 01:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jahorina', '0003_category_message_alter_skitrack_last_updated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skitrack',
            name='last_updated',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 24, 3, 50, 50, 101011)),
        ),
    ]
